name: Build and Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build project
      run: npm run build
      
    - name: Create deployment archive
      run: |
        cd dist
        tar -czf ../site.tar.gz .
        cd ..
        
    - name: Deploy to VPS using rsync
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.git*' --exclude='node_modules'
        path: dist/
        remote_path: /var/www/html/
        remote_host: ${{ secrets.VPS_HOST }}
        remote_user: ${{ secrets.VPS_USERNAME }}
        remote_key: ${{ secrets.VPS_SSH_KEY }}
        remote_port: ${{ secrets.VPS_PORT }}
        
    - name: Set permissions and reload web server
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: fifsky/ssh-action@master
      with:
        command: |
          # Set proper permissions
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          
          # Restart web server (adjust as needed for your setup)
          sudo systemctl reload nginx || sudo systemctl reload apache2 || echo "Web server reload not needed"
          
          echo "Deployment completed successfully!"
        host: ${{ secrets.VPS_HOST }}
        user: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}