name: Build and Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build project
      run: npm run build
      
    - name: Create deployment archive
      run: |
        cd dist
        tar -czf ../site.tar.gz .
        cd ..
        
    - name: Deploy to VPS
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Create backup of current site
          if [ -d "/var/www/html" ] && [ "$(ls -A /var/www/html)" ]; then
            sudo cp -r /var/www/html /var/www/html.backup.$(date +%Y%m%d_%H%M%S)
          fi
          
          # Create web directory if it doesn't exist
          sudo mkdir -p /var/www/html
          
          # Set proper ownership
          sudo chown -R www-data:www-data /var/www/html
          
    - name: Copy files to VPS
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        source: "site.tar.gz"
        target: "/tmp/"
        
    - name: Extract and deploy files
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Clear current web directory
          sudo rm -rf /var/www/html/*
          
          # Extract new files
          cd /var/www/html
          sudo tar -xzf /tmp/site.tar.gz
          
          # Set proper permissions
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          
          # Clean up
          rm -f /tmp/site.tar.gz
          
          # Restart web server (adjust as needed for your setup)
          sudo systemctl reload nginx || sudo systemctl reload apache2 || echo "Web server reload not needed"
          
          echo "Deployment completed successfully!"